# Generated by Django 5.0 on 2024-01-01 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('legenda', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('data_e_hora', models.DateTimeField()),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.funcionario')),
            ],
        ),
    ]
